サインアウト実装
kikudesuyo/pratan pull request #37
Opened 2024-07-23 08:38 UTC by kikudesuyo

- https://github.com/kikudesuyo/pratan/issues/35

2024-07-23 08:38 UTC, kikudesuyo commented
@eteRnaL198 
レビューお願いします

2024-07-23 13:18 UTC, eteRnaL198 requested changes

2024-07-23 13:18 UTC, eteRnaL198 commented on src/stores/user.ts
> +  clearUserId: () => set({ userId: null }),
これ分かりやすくていいね

2024-07-23 13:18 UTC, eteRnaL198 commented on src/components/Sidebar.tsx
> +  const handleSignout = async () => {
`signOut`なのか`signout`なのか統一したいな

firebase的には`auth.signOut()`があるから`signOut`っぽいね
`signout`で1単語にしても良いような気がする
どっちにしますか

2024-07-25 05:24 UTC, kikudesuyo commented on src/components/Sidebar.tsx
> +  const handleSignout = async () => {
ほんとだ。
firebaseがsignOutだからsignOutがいい気がすす

2024-07-25 05:59 UTC, kikudesuyo commented
@eteRnaL198 
レビューお願いします

2024-07-25 06:55 UTC, eteRnaL198 approved these changes
LGTM‼︎

2024-07-28 04:27 UTC, merged