同一の単語を登録できないようにした
kikudesuyo/pratan pull request #42
Opened 2024-07-28 05:32 UTC by kikudesuyo

2024-07-28 06:48 UTC, eteRnaL198 requested changes

2024-07-28 06:48 UTC, eteRnaL198 commented on src/pages/WordList.tsx
> +        (word) => word.spell.toLowerCase() === newWordSpell.toLowerCase()
`features/addWord.ts`に`addWord`関数を定義して、それを呼び出す形にしたい。
addWord関数で↓をする
- 重複があったら早期return
- firebaseに追加
- zustandのstoreに追加
こっちの方がTell, Don't Askっぽくなる

あと、現状はwordに関するロジックが分散しちゃってるから、どこかのタイミングでリファクタリングをして1つに凝集させたいな

2024-07-28 07:30 UTC, kikudesuyo commented on src/pages/WordList.tsx
> +        (word) => word.spell.toLowerCase() === newWordSpell.toLowerCase()
addWord関数を実装する際に、useId, newWord, wordsが必要になるけど、3つを引数にもたせていいの?
それともaddWord関数内でuseIdとwordsを取得して、newWordだけを引数とするべき?

3つの場合
``` features/addWord.ts
import { Word } from "@/utils/types";
import { registerWord } from "@/features/registerWord";
import { addWord as addWordWithZustand } from "@/stores/words";

export const addWord = async (
  userId: string,
  newWord: string,
  words: Word[]
) => {
  if (
    words.some((word) => word.spell.toLowerCase() === newWord.toLowerCase())
  ) {
    alert("This word is already in the list");
    throw new Error("This word is already in the list");
  }
  const word = await registerWord(userId, newWord);
  addWordWithZustand(word);
};
```

1つの場合
```features/addWord.ts
import { Word } from "@/utils/types";
import { registerWord } from "@/features/registerWord";
import { addWord as addWordWithZustand } from "@/stores/words";

export const addWord = async (
  userId: string,
  newWord: string,
  words: Word[]
) => {
  if (
    words.some((word) => word.spell.toLowerCase() === newWord.toLowerCase())
  ) {
    alert("This word is already in the list");
    throw new Error("This word is already in the list");
  }
  const word = await registerWord(userId, newWord);
  addWordWithZustand(word);
};
```

個人的には、zushandはこのプロジェクトの根幹のものだから内部で読み込んでもいいのかなーとは思うけど、どうなんだろう??

今回みたいに、関数にどれだけ責任をもたせるのかを理解しきれていないので教えてほしいですー

2024-07-28 11:52 UTC, eteRnaL198 commented on src/pages/WordList.tsx
> +        (word) => word.spell.toLowerCase() === newWordSpell.toLowerCase()
> addWord関数を実装する際に、useId, newWord, wordsが必要になるけど、3つを引数にもたせていいの?
それともaddWord関数内でuseIdとwordsを取得して、newWordだけを引数とするべき?

内部で読み込むのが良いと思う。関数の引数は少ないほうが認知負荷が抑えられるからよい。

> 今回みたいに、関数にどれだけ責任をもたせるのかを理解しきれていないので教えてほしいですー

凝集度が高くなるように関数の中身を考えるのがよいと思う。
[良いコードとは何か - エンジニア新卒研修 スライド公開](https://note.com/cyberz_cto/n/n26f535d6c575)
addWordはwordを扱う処理のまとまりだから通信的凝集かな。これは良い凝集。

2024-07-29 01:42 UTC, kikudesuyo commented on src/pages/WordList.tsx
> +        (word) => word.spell.toLowerCase() === newWordSpell.toLowerCase()
めちゃめちゃ良い資料だね。
通信的凝集と逐次的凝集のコードを書くときに、いつも困ってたけどある程度はしょうがないのか。
ちょっと理解できたかも

2024-07-29 02:17 UTC, kikudesuyo commented on src/pages/WordList.tsx
> +        (word) => word.spell.toLowerCase() === newWordSpell.toLowerCase()
[7ed2d0c](https://github.com/kikudesuyo/pratan/pull/42/commits/7ed2d0cf3a583f84f754d03c609dbe566f0f7406)
修正しました。コンポーネント内にロジックが無くなり非常に良くなりました

2024-07-29 02:18 UTC, kikudesuyo commented
[f6023f8](https://github.com/kikudesuyo/pratan/pull/42/commits/f6023f80abb1ea5d92eced464954bfadd26453b4)
レビューお願いします。
useは状態が変わってしまうので、getの方がいい気がしたけどどうだろう

2024-07-29 02:36 UTC, eteRnaL198 requested changes

2024-07-29 02:36 UTC, eteRnaL198 commented on src/pages/WordList.tsx
> +  const words = useWordsStore.getState().words;
get良いね。直感的に分かりやすい気がする

2024-07-29 02:36 UTC, eteRnaL198 commented on src/features/addWord.ts
> +export const addWord = async (newWord: string) => {
引数は`spell`がいいかも

2024-07-29 02:39 UTC, kikudesuyo commented on src/pages/WordList.tsx
> +  const words = useWordsStore.getState().words;
`words`が変化するのは、`handleAddClick`関数内なので`get`でいいのかなって思いました。

pages/WordList.tsx、stores/words.ts、features/addWord.tsのいずれかで状態が変化すると思うけど、単語の状態の変化をどこでするべきなのかな?
構造が宜しく無い気がします。改良の余地がありそう。

2024-07-29 02:42 UTC, kikudesuyo commented on src/features/addWord.ts
> +export const addWord = async (newWord: string) => {
たしかに、修正しました
[61c69f6](https://github.com/kikudesuyo/pratan/pull/42/commits/61c69f64ef21c1f19c9e56752e4518a8b0dbdab4)

2024-07-29 02:45 UTC, kikudesuyo commented
### wordsの状態管理について

pages/WordList.tsx、stores/words.ts、features/addWord.tsのいずれかで状態が変化すると思うけど、単語の状態の更新をどこでするべきなのかな?
構造が宜しく無い気がします。改良の余地がありそう。

2024-07-29 02:46 UTC, kikudesuyo commented on src/pages/WordList.tsx
> +  const words = useWordsStore.getState().words;
標準でそういうのがあった
他も修正していいかな?

2024-07-29 03:55 UTC, eteRnaL198 commented on src/pages/WordList.tsx
> +  const words = useWordsStore.getState().words;
そうねー
そこまで大事な書き換えでもないから 気が向いた時でいいよ

2024-07-29 04:00 UTC, eteRnaL198 commented
> ### wordsの状態管理について
> 
> 
> 
> pages/WordList.tsx、stores/words.ts、features/addWord.tsのいずれかで状態が変化すると思うけど、単語の状態の更新をどこでするべきなのかな?
> 
> 構造が宜しく無い気がします。改良の余地がありそう。

階層構造になってるイメージだった
pages → feature → stores&firebase

Notionで起票したみたいに、技術駆動じゃなくてドメイン？駆動にすればもうちょっとまとまり感を強くできる気がする

2024-07-29 04:39 UTC, kikudesuyo commented on src/pages/WordList.tsx
> +  const words = useWordsStore.getState().words;
修正しましたー
[e806f00](https://github.com/kikudesuyo/pratan/pull/42/commits/e806f00813c66ce3a846889cbbde607078a1706a)

2024-07-29 04:43 UTC, kikudesuyo commented
> > ### wordsの状態管理について
> > pages/WordList.tsx、stores/words.ts、features/addWord.tsのいずれかで状態が変化すると思うけど、単語の状態の更新をどこでするべきなのかな?
> > 構造が宜しく無い気がします。改良の余地がありそう。
> 
> 階層構造になってるイメージだった pages → feature → stores&firebase
> 
> ほんとはこの間にカスタムフックを挟みたい pages → _hook_ → feature → stores&firebase
> 
> Notionで起票したみたいに、技術駆動じゃなくてドメイン？駆動にすればもうちょっとまとまり感を強くできる気がする

それかもしれない、現状stores、firebaseに保存してるのが読み取りにくいんだよね

2024-07-29 05:11 UTC, eteRnaL198 commented
> それかもしれない、現状stores、firebaseに保存してるのが読み取りにくいんだよね

どう保存してるかはfeatureなりHooksなりに全部隠蔽して、呼び出し時には気にしないようにしたい

2024-07-29 05:13 UTC, eteRnaL198 commented
> 状態管理のリファクタについては別のプルリクでやる感じでいいよね?

うん

2024-07-29 05:18 UTC, kikudesuyo commented
> どう保存してるかはfeatureなりHooksなりに全部隠蔽して、呼び出し時には気にしないようにしたい 今は中途半端にfeature使ったりstoreを直接呼び出したりしてるから分かりづらくなっちゃってるのかも

なるほど、確かに知らなくていいのか。中途半端になってて嫌だな。
一度リファクタしたいかも

2024-07-29 05:19 UTC, kikudesuyo commented
一旦プルリク閉じていいかな?

2024-07-29 05:21 UTC, eteRnaL198 commented
> なるほど、確かに知らなくていいのか。中途半端になってて嫌だな。
一度リファクタしたいかも

リファクタしよう
今回は相当急いで妥協しながら書いたから、気になってるところが沢山ある

2024-07-29 05:21 UTC, eteRnaL198 approved these changes
LGTM

2024-07-29 05:29 UTC, merged